# Generated by Django 3.2.5 on 2023-09-09 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo_number', models.CharField(db_index=True, max_length=10, unique=True)),
                ('started_at', models.DateField()),
                ('finished_at', models.DateField()),
                ('order_type', models.CharField(choices=[('cleaning', 'Cleaning'), ('maid_request', 'Maid Request'), ('technician_request', 'Technician Request'), ('amenity_request', 'Amenity Request')], max_length=20)),
                ('order_status', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancel', 'Cancel'), ('cancel_by_guest', 'Cancel By Guest')], default='created', max_length=20)),
                ('remark', models.TextField(blank=True, null=True)),
                ('problem', models.CharField(choices=[('electricity', 'Electricity'), ('air_conditioning', 'Air Conditioning'), ('plumbing', 'Plumbing'), ('internet', 'Internet')], default=None, max_length=20, null=True)),
                ('amenity_name', models.CharField(blank=True, max_length=100, null=True)),
                ('amenity_count', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_assign', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_create', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_room', to='rooms.room')),
            ],
        ),
    ]
